{lang;cs}
{set;~p;{get;@{userid}chess_instance}}
{set;~a;1}{set;~1;a}{set;~b;2}{set;~2;b}{set;~c;3}{set;~3;c}{set;~d;4}{set;~4;d}{set;~e;5}{set;~5;e}{set;~f;6}{set;~6;f}{set;~g;7}{set;~7;g}{set;~h;8}{set;~8;h}
{set;~link;{get;@chess_link1}{set;~index0;1}{set;~index1;1}{regexreplace;{repeat;{get;@{get;~p}{get;~{get;~index0}}{get;~index1}}{if;==;8;{get;~index0};{set;~index0;1}{void;{increment;~index1}};{void;{increment;~index0}}};64};/-/g;_}&p={get;@{userid}chess_sizen}&s={get;@{userid}chess_piecen}&c={get;@{userid}chess_color_darkn}{get;@{userid}chess_color_lightn}000000000000{switch;{get;@{userid}chess_coordn};;&r=FFFFFF;nc;;o;&r=FFFFFF;&r=FFFFFF}{set;~k;{if;{logic;&&;{if;!=;;{get;~{get;~p}1a};true;false};{if;!=;;{get;~{get;~p}1b};true;false}};{get;~{get;~p}1a}Q{get;~{get;~p}1b}Q0Q0Q255A}{if;{logic;&&;{if;!=;;{get;~{get;~p}2a};true;false};{if;!=;;{get;~{get;~p}2b};true;false}};{get;~{get;~p}2a}Q{get;~{get;~p}2b}{if;==;true;{get;~{get;~p}eat};Q255Q0Q0;Q0Q0Q255}}}{if;!=;;{get;~k};&k={get;~k}}&z={get;@{get;~p}tm}{if;==;b;{get;@{get;~p}tm};&f=1}}
{embed;
	{buildembed;
		author.icon_url:
			{useravatar};
		author.name:
			{usernick};
		color:
			{exec;chess_color};
		description:
			**[Board]({get;~link})**;
		footer.icon_url:
			{if;==;w;{get;@{get;~p}tm};
				https://cdn.discordapp.com/emojis/432200723724369920.png;
				https://cdn.discordapp.com/emojis/432200721820155924.png
			};
		footer.text:
			{if;==;w;{get;@{get;~p}tm};White;Black} to move - {username;{get;@{get;~p}p{if;==;w;{get;@{get;~p}tm};1;2}}}{get;@aph}s turn;
		image.url:
			{get;~link};
		{if;!=;;{get;@{get;~p}previous};
			thumbnail.url:
			{get;@{get;~p}previous}
		};
		timestamp:
			{time};
		title:
			{get;@{get;~p}move}{switch;{get;@{get;~p}move};11;ᵗʰ;12;ᵗʰ;13;ᵗʰ;{switch;{substring;{get;@{get;~p}move};{math;-;{length;{get;@{get;~p}move}};1}};1;ˢᵗ;2;ⁿᵈ;3;ʳᵈ;ᵗʰ}} Move;
	}
}