{set;@{get;~p}unmoved$k;1}
{set;@{get;~p}unmoved$K;1}
{set;@{get;~p}unmoved$r_a8;1}
{set;@{get;~p}unmoved$r_h8;1}
{set;@{get;~p}unmoved$R_a1;1}
{set;@{get;~p}unmoved$R_h1;1}
{set;@{get;~p}unmoved$p_a7;1}
{set;@{get;~p}unmoved$p_b7;1}
{set;@{get;~p}unmoved$p_c7;1}
{set;@{get;~p}unmoved$p_d7;1}
{set;@{get;~p}unmoved$p_e7;1}
{set;@{get;~p}unmoved$p_f7;1}
{set;@{get;~p}unmoved$p_g7;1}
{set;@{get;~p}unmoved$p_h7;1}
{set;@{get;~p}unmoved$P_a2;1}
{set;@{get;~p}unmoved$P_b2;1}
{set;@{get;~p}unmoved$P_c2;1}
{set;@{get;~p}unmoved$P_d2;1}
{set;@{get;~p}unmoved$P_e2;1}
{set;@{get;~p}unmoved$P_f2;1}
{set;@{get;~p}unmoved$P_g2;1}
{set;~p;{get;@{userid}chess_instance}}
{set;@{get;~p}unmoved$P_h2;1}
{set;@{get;~p}a8;r}{set;@{get;~p}a7;p}{set;@{get;~p}a6;-}{set;@{get;~p}a5;-}
{set;@{get;~p}b8;n}{set;@{get;~p}b7;p}{set;@{get;~p}b6;-}{set;@{get;~p}b5;-}
{set;@{get;~p}c8;b}{set;@{get;~p}c7;p}{set;@{get;~p}c6;-}{set;@{get;~p}c5;-}
{set;@{get;~p}d8;q}{set;@{get;~p}d7;p}{set;@{get;~p}d6;-}{set;@{get;~p}d5;-}
{set;@{get;~p}e8;k}{set;@{get;~p}e7;p}{set;@{get;~p}e6;-}{set;@{get;~p}e5;-}
{set;@{get;~p}f8;b}{set;@{get;~p}f7;p}{set;@{get;~p}f6;-}{set;@{get;~p}f5;-}
{set;@{get;~p}g8;n}{set;@{get;~p}g7;p}{set;@{get;~p}g6;-}{set;@{get;~p}g5;-}
{set;@{get;~p}h8;r}{set;@{get;~p}h7;p}{set;@{get;~p}h6;-}{set;@{get;~p}h5;-}
{set;@{get;~p}a4;-}{set;@{get;~p}a3;-}{set;@{get;~p}a2;P}{set;@{get;~p}a1;R}
{set;@{get;~p}b4;-}{set;@{get;~p}b3;-}{set;@{get;~p}b2;P}{set;@{get;~p}b1;N}
{set;@{get;~p}c4;-}{set;@{get;~p}c3;-}{set;@{get;~p}c2;P}{set;@{get;~p}c1;B}
{set;@{get;~p}d4;-}{set;@{get;~p}d3;-}{set;@{get;~p}d2;P}{set;@{get;~p}d1;Q}
{set;@{get;~p}e4;-}{set;@{get;~p}e3;-}{set;@{get;~p}e2;P}{set;@{get;~p}e1;K}
{set;@{get;~p}f4;-}{set;@{get;~p}f3;-}{set;@{get;~p}f2;P}{set;@{get;~p}f1;B}
{set;@{get;~p}g4;-}{set;@{get;~p}g3;-}{set;@{get;~p}g2;P}{set;@{get;~p}g1;N}
{set;@{get;~p}h4;-}{set;@{get;~p}h3;-}{set;@{get;~p}h2;P}{set;@{get;~p}h1;R}
{set;~chess_link;
	http://www.jinchess.com/chessboard/?p=	
}**Reset Board!**
{get;~chess_link}{get;@{get;~p}a8}{get;@{get;~p}b8}{get;@{get;~p}c8}{get;@{get;~p}d8}{get;@{get;~p}e8}{get;@{get;~p}f8}{get;@{get;~p}g8}{get;@{get;~p}h8}{get;@{get;~p}a7}{get;@{get;~p}b7}{get;@{get;~p}c7}{get;@{get;~p}d7}{get;@{get;~p}e7}{get;@{get;~p}f7}{get;@{get;~p}g7}{get;@{get;~p}h7}{get;@{get;~p}a6}{get;@{get;~p}b6}{get;@{get;~p}c6}{get;@{get;~p}d6}{get;@{get;~p}e6}{get;@{get;~p}f6}{get;@{get;~p}g6}{get;@{get;~p}h6}{get;@{get;~p}a5}{get;@{get;~p}b5}{get;@{get;~p}c5}{get;@{get;~p}d5}{get;@{get;~p}e5}{get;@{get;~p}f5}{get;@{get;~p}g5}{get;@{get;~p}h5}{get;@{get;~p}a4}{get;@{get;~p}b4}{get;@{get;~p}c4}{get;@{get;~p}d4}{get;@{get;~p}e4}{get;@{get;~p}f4}{get;@{get;~p}g4}{get;@{get;~p}h4}{get;@{get;~p}a3}{get;@{get;~p}b3}{get;@{get;~p}c3}{get;@{get;~p}d3}{get;@{get;~p}e3}{get;@{get;~p}f3}{get;@{get;~p}g3}{get;@{get;~p}h3}{get;@{get;~p}a2}{get;@{get;~p}b2}{get;@{get;~p}c2}{get;@{get;~p}d2}{get;@{get;~p}e2}{get;@{get;~p}f2}{get;@{get;~p}g2}{get;@{get;~p}h2}{get;@{get;~p}a1}{get;@{get;~p}b1}{get;@{get;~p}c1}{get;@{get;~p}d1}{get;@{get;~p}e1}{get;@{get;~p}f1}{get;@{get;~p}g1}{get;@{get;~p}h1}&tm={get;@{get;~p}tm}{if;==;m;{get;@{userid}ch_size};;&s={get;@{userid}ch_size}}&tt={username;{get;@{get;~p}p2}}&ct={username;{get;@{get;~p}p1}}{switch;{get;@{userid}chess_board};;;plain;;&bp={get;@{userid}chess_board}}{switch;{get;@{userid}chess_board};;;alpha;;&ps={get;@{userid}chess_piece}}{switch;{get;@{userid}ch_coord};;&cm=o;nc;;&cm={get;@{userid}ch_coord}}{return}