{if;{logic;!;{iscc}};{return;false}}
{if;{length;{get;~L}};<=;1;{return;false}}
{set;~states;
	Alabama;Alaska;Arizona;Arkansas;Armed Forces America;Armed Forces Europe;Armed Forces Pacific;California;Colorado;Connecticut;Delaware;District of Columbia;Florida;Georgia;Hawaii;Idaho;Illinois;Indiana;Iowa;Kansas;Kentucky;Louisiana;Maine;Maryland;Massachusetts;Michigan;Minnesota;Mississippi;Missouri;Montana;Nebraska;Nevada;New Hampshire;New Jersey;New Mexico;New York;North Carolina;North Dakota;Ohio;Oklahoma;Oregon;Pennsylvania;Rhode Island;South Carolina;South Dakota;Tennessee;Texas;Utah;Vermont;Virginia;Washington;West Virginia;Wisconsin;Wyoming
}
{set;~state_code;
	AL;AK;AZ;AR;AA;AE;AP;CA;CO;CT;DE;DC;FL;GA;HI;ID;IL;IN;IA;KS;KY;LA;ME;MD;MA;MI;MN;MS;MO;MT;NE;NV;NH;NJ;NM;NY;NC;ND;OH;OK;OR;PA;RI;SC;SD;TN;TX;UT;VT;VA;WA;WV;WI;WY
}
{set;~provinces;
	Alberta;British Columbia;Manitoba;New Brunswick;Newfoundland and Labrador;Northwest Territories;Nova Scotia;Nunavut;Ontario;Prince Edward Island;Quebec;Saskatchewan;Yukon
}
{set;~province_code;
	AB;BC;MB;NB;NL;NT;NS;NU;ON;PE;QC;SK;YT
}
{set;~countries;
	Afghanistan;Albania;Algeria;Andorra;Angola;Antigua and Barbuda;Argentina;Armenia;Australia;Austria;Azerbaijan;Bahamas;Bahrain;Bangladesh;Barbados;Belarus;Belgium;Belize;Benin;Bhutan;Bolivia (Plurinational State of);Bosnia and Herzegovina;Botswana;Brazil;Brunei Darussalam;Bulgaria;Burkina Faso;Burundi;Cabo Verde;Cambodia;Cameroon;Canada;Central African Republic;Chad;Chile;China;Colombia;Comoros;Congo;Cook Islands;Costa Rica;Croatia;Cuba;Cyprus;Czechia;Côte d'Ivoire;Democratic People's Republic of Korea;Democratic Republic of the Congo;Denmark;Djibouti;Dominica;Dominican Republic;Ecuador;Egypt;El Salvador;Equatorial Guinea;Eritrea;Estonia;Ethiopia;Faroe Islands (Associate Member);Fiji;Finland;France;Gabon;Gambia;Georgia;Germany;Ghana;Gr	eece;Grenada;Guatemala;Guinea;Guinea-Bissau;Guyana;Haiti;Honduras;Hungary;Iceland;India;Indonesia;Iran (Islamic Republic of);Iraq;Ireland;Israel;Italy;Jamaica;Japan;Jordan;Kazakhstan;Kenya;Kiribati;Kuwait;Kyrgyzstan;Lao People's Democratic Republic;Latvia;Lebanon;Lesotho;Liberia;Libya;Lithuania;Luxembourg;Madagascar;Malawi;Malaysia;Maldives;Mali;Malta;Marshall Islands;Mauritania;Mauritius;Mexico;Micronesia (Federated States of);Monaco;Mongolia;Montenegro;Morocco;Mozambique;Myanmar;Namibia;Nauru;Nepal;Netherlands;New Zealand;Nicaragua;Niger;Nigeria;Niue;Norway;Oman;Pakistan;Palau;Panama;Papua New Guinea;Paraguay;Peru;Philippines;Poland;Portugal;Qatar;Republic of Korea;Republic of Moldova;Romania;Russian Federation;Rwanda;Saint Kitts and Nevis;Saint Lucia;Saint Vincent and the Grenadines;Samoa;San Marino;Sao Tome and Principe;Saudi Arabia;Senegal;Serbia;Seychelles;Sierra Leone;Singapore;Slovakia;Slovenia;Solomon Islands;Somalia;South Africa;South Sudan;Spain;Sri Lanka;Sudan;Suriname;Swaziland;Sweden;Switzerland;Syrian Arab Republic;Tajikistan;Thailand;The former Yugoslav Republic of Macedonia;Timor-Leste;Togo;Tokelau (Associate Member);Tonga;Trinidad and Tobago;Tunisia;Turkey;Turkmenistan;Tuvalu;Uganda;Ukraine;United Arab Emirates;United Kingdom;United Republic of Tanzania;United States of America;Uruguay;Uzbekistan;Vanuatu;Venezuela (Bolivarian Republic of);Viet Nam;Yemen;Zambia;Zimbabwe
}
{set;~iso2;
	AF;AL;DZ;AD;AO;AG;AR;AM;AU;AT;AZ;BS;BH;BD;BB;BY;BE;BZ;BJ;BT;BO;BA;BW;BR;BN;BG;BF;BI;CV;KH;CM;CA;CF;TD;CL;CN;CO;KM;CG;CK;CR;HR;CU;CY;CZ;CI;KP;CD;DK;DJ;DM;DO;EC;EG;SV;GQ;ER;EE;ET;FO;FJ;FI;FR;GA;GM;GE;DE;GH;GR;GD;GT;GN;GW;GY;HT;HN;HU;IS;IN;ID;IR;IQ;IE;IL;IT;JM;JP;JO;KZ;KE;KI;KW;KG;LA;LV;LB;LS;LR;LY;LT;LU;MG;MW;MY;MV;ML;MT;MH;MR;MU;MX;FM;MC;MN;ME;MA;MZ;MM;NA;NR;NP;NL;NZ;NI;NE;NG;NU;NO;OM;PK;PW;PA;PG;PY;PE;PH;PL;PT;QA;KR;MD;RO;RU;RW;KN;LC;VC;WS;SM;ST;SA;SN;RS;SC;SL;SG;SK;SI;SB;SO;ZA;SS;ES;LK;SD;SR;SZ;SE;CH;SY;TJ;TH;MK;TL;TG;TK;TO;TT;TN;TR;TM;TV;UG;UA;AE;GB;TZ;US;UY;UZ;VU;VE;VN;YE;ZM;ZW
}
{set;~iso3;
	AFG;ALB;DZA;AND;AGO;ATG;ARG;ARM;AUS;AUT;AZE;BHS;BHR;BGD;BRB;BLR;BEL;BLZ;BEN;BTN;BOL;BIH;BWA;BRA;BRN;BGR;BFA;BDI;CPV;KHM;CMR;CAN;CAF;TCD;CHL;CHN;COL;COM;COG;COK;CRI;HRV;CUB;CYP;CZE;CIV;PRK;COD;DNK;DJI;DMA;DOM;ECU;EGY;SLV;GNQ;ERI;EST;ETH;FRO;FJI;FIN;FRA;GAB;GMB;GEO;DEU;GHA;GRC;GRD;GTM;GIN;GNB;GUY;HTI;HND;HUN;ISL;IND;IDN;IRN;IRQ;IRL;ISR;ITA;JAM;JPN;JOR;KAZ;KEN;KIR;KWT;KGZ;LAO;LVA;LBN;LSO;LBR;LBY;LTU;LUX;MDG;MWI;MYS;MDV;MLI;MLT;MHL;MRT;MUS;MEX;FSM;MCO;MNG;MNE;MAR;MOZ;MMR;NAM;NRU;NPL;NLD;NZL;NIC;NER;NGA;NIU;NOR;OMN;PAK;PLW;PAN;PNG;PRY;PER;PHL;POL;PRT;QAT;KOR;MDA;ROU;RUS;RWA;KNA;LCA;VCT;WSM;SMR;STP;SAU;SEN;SRB;SYC;SLE;SGP;SVK;SVN;SLB;SOM;ZAF;SSD;ESP;LKA;SDN;SUR;SWZ;SWE;CHE;SYR;TJK;THA;MKD;TLS;TGO;TKL;TON;TTO;TUN;TUR;TKM;TUV;UGA;UKR;ARE;GBR;TZA;USA;URY;UZB;VUT;VEN;VNM;YEM;ZMB;ZWE
}
{set;~w-us;WA;ID;MT;OR;WY;CA;NV;UT;CO}
{set;~mw-us;ND;SD;NE;KS;MN;IA;MO;WI;IL;MI;IN;OH}
{set;~sw-us;AZ;NM;TX;OK}
{set;~se-us;AR;LA;KY;TN;MS;AL;WV;MD;DE;DC;VA;NC;SC;GA;FL}
{set;~ne-us;PA;NY;NJ;ME;NH;VT;MA;CT;RI}
{if;{indexof;{get;~state_code};{upper;{get;~L}}};!=;-1;
	{set;_{userid}location;{get;~states;{indexof;{get;~state_code};{upper;{get;~L}}}}}
	{switch;{upper;{get;~L}};
		{get;~w-us};{void;{roleadd;455357627719745536}};
		{get;~mw-us};{void;{roleadd;456795518467702798}};
		{get;~sw-us};{void;{roleadd;453958480089448459}};
		{get;~se-us};{void;{roleadd;455791164931702795}};
		{get;~ne-us};{void;{roleadd;453957028243701764}}
	}
	{return;false}
}
{if;{indexof;{get;~province_code};{upper;{get;~L}}};!=;-1;
	{set;_{userid}location;{get;~province;{indexof;{get;~province_code};{upper;{get;~L}}}}}
	{void;{roleadd;455788879958507521}}
	{return;false}
}
{set;~europe;Russian Federation;Germany;United Kingdom;France;Italy;Spain;Ukraine;Poland;Romania;Netherlands;Belgium;Greece;Czechia;Portugal;Sweden;Hungary;Belarus;Serbia;Austria;Switzerland;Bulgaria;Denmark;Finland;Slovakia;Norway;Ireland;Croatia;Republic of Moldova;Bosnia and Herzegovina;Albania;Lithuania;The former Yugoslav Republic of Macedonia;Slovenia;Latvia;Estonia;Montenegro;Luxembourg;Malta;Iceland;Andorra;Monaco;San Marino}
{set;~oceania;Australia;Papua New Guinea;New Zealand;Fiji;Solomon Islands;Vanuatu;Samoa;Kiribati;Tonga;Micronesia (Federated States of);Marshall Islands;Palau;Nauru;Tuvalu}
{if;{indexof;{get;~iso2};{upper;{get;~L}}};!=;-1;
	{set;_{userid}location;{get;~countries;{indexof;{get;~iso2};{upper;{get;~L}}}}}
	{switch;{get;_{userid}location};
		{get;~europe};{void;{roleadd;455357588507328533}};
		{get;~oceania};{void;{roleadd;455788076468535322}}
	}
	{return;false}
}
{if;{indexof;{get;~iso3};{upper;{get;~L}}};!=;-1;
	{set;_{userid}location;{get;~countries;{indexof;{get;~iso3};{upper;{get;~L}}}}}
	{switch;{get;_{userid}location};
		{get;~europe};{void;{roleadd;455357588507328533}};
		{get;~oceania};{void;{roleadd;455788076468535322}}
	}
	{return;false}
}
{set;~l;[]}
{foreach;~state;~states;
	{if;{lower;{get;~state}};includes;{lower;{get;~L}};
		{push;~l;{get;~state}}
	}
}
{foreach;~province;~provinces;
	{if;{lower;{get;~province}};includes;{lower;{get;~L}};
		{push;~l;{get;~province}}
	}
}
{foreach;~country;~countries;
	{if;{lower;{get;~country}};includes;{lower;{get;~L}};
		{push;~l;{get;~country}}
	}
}
{switch;{length;{get;~l}};
	0;{set;_{userid}location;{get;~L;0}};
	1;{set;_{userid}location;{get;~l;0}};
	{execcc;option}{set;_{userid}location;{get;~item;0}}
}
{switch;{get;_{userid}location};
	{get;~europe};{void;{roleadd;455357588507328533}};
	{get;~oceania};{void;{roleadd;455788076468535322}};
	{get;~provinces};{void;{roleadd;455788879958507521}};
	{get;~states};
		{switch;{get;~state_code;{indexof;{get;~states};{get;_{userid}location}}};
			{get;~w-us};{void;{roleadd;455357627719745536}};
			{get;~mw-us};{void;{roleadd;456795518467702798}};
			{get;~sw-us};{void;{roleadd;453958480089448459}};
			{get;~se-us};{void;{roleadd;455791164931702795}};
			{get;~ne-us};{void;{roleadd;453957028243701764}}
		}
}