{if;==;NaN;{parseint;{get;@{userid}ocredits}};
	{set;@{userid}ocredits;0}
}
{if;==;{get;@{userid}ocredits};{get;@{userid}credits};
	{void};
	{set;@{userid}ocredits;{get;@{userid}credits}}
	{set;@0;
		{regexreplace;
			{get;@ldboard};
			/(\d+#)(\d{1,18})/g;
			$2
		}
	}
	{set;~nw;{pad;left;{repeat;0;{get;@crlength}};0{get;@{userid}credits}}}
	{if;==;-1;{indexof;{get;@0};{userid}};
		{push;{get;@ldboard};
			{get;@{userid}credits}#{userid}
		};
		{void;
			{splice;{get;@ldboard};
				{indexof;{get;@0};{userid}};1;
				{get;~nw}
			}
		}
	}
	{sort;{get;@ldboard};descending}
}