{set;~valid_flags;d;c;t;k;e;m;r}
{//;
	d:description
	c:color
	e:emoji
	t:time
	k:key
	m:message
	r:role
}
{set;~emoji;:tada:}
{set;~title;Giveaway}
{set;~flags;{split;{args};-}}
{set;~title;{shift;{get;~flags}}}
{foreach;~f;~flags;
	{set;~r;{substring;{get;~f};0;1}}
	{set;~i;{substring;{get;~f};2}}
	{set;~v;{indexof;{get;~valid_flags};{get;~r}}}
	{if;!=;-1;{get;~v};
		{switch;{get;~r};
			d;{set;~description;{get;~i}};
			c;{set;~color;{get;~i}};
			e;{set;~emoji;{get;~i}};
			t;{set;~time;{get;~i}};
			k;{set;~key;{get;~i}};
			m;{set;~message;{get;~i}};
			r;{set;~role;{roleid;{get;~i}}}
		}
		{void;{splice;~valid_flags;{get;~v};1}}
	}
}
{set;~m;**A giveaway has started! React {get;~emoji} to join!**{newline}{get;~m}}
{if;{get
{set;~msg;
	{send;{channelid};
		{buildembed;
			title:{get;~title};
			description:{get;~description};
			
{addreact;{get;~msg};:tada:}
{timer;
	Users to pick from (Example) {foreach;~user;{reactlist;{get;~msg};:tada:};{username;{get;~user}}#{userdiscrim;{get;~user}}};30s}